libs =

import libs += libmoltenvk%lib{MoltenVK} \
               libspirv-cross%lib{spirv-cross-msl}

exe{MoltenVKShaderConverter}: {h cxx mm}{*} $libs

# Symlinked .cpp/.mm resolve includes against their real upstream paths.
#
cxx.poptions =+ "-I$src_base"
